Bootstrap: debootstrap
OSVersion: stretch
MirrorURL: http://ftp.ca.debian.org/debian/

%files
        Gblast2

%environment
export HMMTOP_ARCH=/var/www/html/Gblast2/hmmtop.arch
export HMMTOP_PSV=/var/www/html/Gblast2/hmmtop.psv

%post
        CPAN_INSTALL_FLAG=-T
	export DEBIAN_FRONTEND=noninteractive
	apt-get update
	apt-get -qqq update
	apt-get -qqq upgrade
	
	apt-get install -y curl apt-utils php
	curl --silent -o apt.gpg https://packages.sury.org/php/apt.gpg
	apt-get install -y ca-certificates lsb-release apt-transport-https dirmngr
	apt-key add /apt.gpg
	apt-get -qqq update
	apt-get -qqq upgrade
	
	apt-get install -y gnupg2 build-essential wget git perl libcurl4-openssl-dev libxml2-dev locales locales-all libexpat1-dev
	ln -fs /usr/share/zoneinfo/America/New_York /etc/localtime
	export LANGUAGE=en_US.UTF-8
	export LANG=en_US.UTF-8
	export LC_ALL=en_US.UTF-8
	locale-gen en_US.UTF-8
	dpkg-reconfigure locales
	
	echo | cpan
	cpan $CPAN_INSTALL_FLAG Test::Needs
	cpan $CPAN_INSTALL_FLAG List::MoreUtils
	cpan $CPAN_INSTALL_FLAG URI
	cpan $CPAN_INSTALL_FLAG IO::HTML
	cpan $CPAN_INSTALL_FLAG IO::String
	cpan $CPAN_INSTALL_FLAG HTTP::Headers
	cpan $CPAN_INSTALL_FLAG HTML::Entities
	cpan $CPAN_INSTALL_FLAG CGI
	cpan $CPAN_INSTALL_FLAG XML::Parser
	cpan $CPAN_INSTALL_FLAG XML::Parser::PerlSAX
	cpan $CPAN_INSTALL_FLAG XML::DOM
	cpan $CPAN_INSTALL_FLAG XML::DOM::XPath
	cpan $CPAN_INSTALL_FLAG Data::Stag
	cpan $CPAN_INSTALL_FLAG XML::Simple
	cpan $CPAN_INSTALL_FLAG XML::Compile::SOAP11
	cpan $CPAN_INSTALL_FLAG XML::Compile::WSDL11
	cpan $CPAN_INSTALL_FLAG XML::Twig
	cpan $CPAN_INSTALL_FLAG File::Which
	cpan $CPAN_INSTALL_FLAG HTML::Template
	cpan $CPAN_INSTALL_FLAG HTML::TreeBuilder
	cpan $CPAN_INSTALL_FLAG JSON
	cpan $CPAN_INSTALL_FLAG Log::Log4perl
	cpan $CPAN_INSTALL_FLAG Math::CDF
	cpan $CPAN_INSTALL_FLAG Bio::SearchIO
	apt-get -y install alien
	curl -s ftp://ftp.ncbi.nlm.nih.gov/blast/executables/blast+/2.2.26/ncbi-blast-2.2.26+-3.x86_64.rpm --output ncbi-blast-2.2.26+-3.x86_64.rpm
	alien -i ncbi-blast-2.2.26+-3.x86_64.rpm
	cp -R Gblast2 /var/www/html/
	chmod 755 /var/www/html/Gblast2/gblast.pl
	chmod 755 /var/www/html/Gblast2/gblast2.php
	chmod 755 /var/www/html/Gblast2/hmmtop
	mv /var/www/html/Gblast2/gblast.pl /usr/local/bin/        
	rm -rf /var/lib/apt/lists/*
